import os

test_base = r"src\test\java\com\kunal\attackpathvisualizer\common\model\snapshot"

content = (
    "package com.kunal.attackpathvisualizer.common.model.snapshot;\n"
    "\n"
    "import org.junit.jupiter.api.Test;\n"
    "import java.time.Instant;\n"
    "import java.util.Arrays;\n"
    "import java.util.HashMap;\n"
    "import java.util.List;\n"
    "import java.util.Map;\n"
    "import static org.junit.jupiter.api.Assertions.*;\n"
    "\n"
    "/**\n"
    " * Unit tests for Phase 4.1 snapshot DTOs (Phase 4.2).\n"
    " */\n"
    "class SnapshotDtoTest {\n"
    "\n"
    "    @Test\n"
    "    void podSnapshot_canBeInstantiatedAndFieldsRoundTrip() {\n"
    "        PodSnapshot pod = new PodSnapshot();\n"
    "        Instant now = Instant.parse(\"2025-01-15T10:00:00Z\");\n"
    "        pod.setUid(\"pod-uid-001\");\n"
    "        pod.setName(\"frontend-pod\");\n"
    "        pod.setNamespace(\"production\");\n"
    "        pod.setCreationTimestamp(now);\n"
    "        pod.setServiceAccountName(\"frontend-sa\");\n"
    "        assertEquals(\"pod-uid-001\", pod.getUid());\n"
    "        assertEquals(\"frontend-pod\", pod.getName());\n"
    "        assertEquals(\"production\", pod.getNamespace());\n"
    "        assertEquals(now, pod.getCreationTimestamp());\n"
    "        assertEquals(\"frontend-sa\", pod.getServiceAccountName());\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void rbacRuleSnapshot_fieldsRoundTrip() {\n"
    "        RbacRuleSnapshot rule = new RbacRuleSnapshot();\n"
    "        rule.setApiGroups(Arrays.asList(\"\", \"apps\"));\n"
    "        rule.setResources(Arrays.asList(\"pods\", \"deployments\"));\n"
    "        rule.setVerbs(Arrays.asList(\"get\", \"list\", \"watch\"));\n"
    "        rule.setResourceNames(Arrays.asList(\"my-resource\"));\n"
    "        assertEquals(2, rule.getApiGroups().size());\n"
    "        assertTrue(rule.getApiGroups().contains(\"apps\"));\n"
    "        assertEquals(2, rule.getResources().size());\n"
    "        assertEquals(3, rule.getVerbs().size());\n"
    "        assertEquals(1, rule.getResourceNames().size());\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void roleSnapshot_canHoldRbacRuleSnapshots() {\n"
    "        RbacRuleSnapshot rule1 = new RbacRuleSnapshot();\n"
    "        rule1.setApiGroups(List.of(\"\"));\n"
    "        rule1.setResources(List.of(\"secrets\"));\n"
    "        rule1.setVerbs(List.of(\"get\", \"list\"));\n"
    "        rule1.setResourceNames(List.of());\n"
    "        RbacRuleSnapshot rule2 = new RbacRuleSnapshot();\n"
    "        rule2.setApiGroups(List.of(\"apps\"));\n"
    "        rule2.setResources(List.of(\"deployments\"));\n"
    "        rule2.setVerbs(List.of(\"create\", \"delete\"));\n"
    "        rule2.setResourceNames(List.of());\n"
    "        RoleSnapshot role = new RoleSnapshot();\n"
    "        role.setUid(\"role-uid-001\");\n"
    "        role.setName(\"read-secrets\");\n"
    "        role.setNamespace(\"default\");\n"
    "        role.setRules(Arrays.asList(rule1, rule2));\n"
    "        assertEquals(\"role-uid-001\", role.getUid());\n"
    "        assertNotNull(role.getRules());\n"
    "        assertEquals(2, role.getRules().size());\n"
    "        assertTrue(role.getRules().get(0).getResources().contains(\"secrets\"));\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void clusterSnapshot_canHoldTypedResourceLists() {\n"
    "        ClusterSnapshot cluster = new ClusterSnapshot();\n"
    "        cluster.setClusterName(\"test-cluster\");\n"
    "        NamespaceSnapshot ns = new NamespaceSnapshot();\n"
    "        ns.setName(\"production\");\n"
    "        cluster.setNamespaces(List.of(ns));\n"
    "        NodeSnapshot node = new NodeSnapshot();\n"
    "        node.setName(\"worker-1\");\n"
    "        cluster.setNodes(List.of(node));\n"
    "        PodSnapshot pod = new PodSnapshot();\n"
    "        pod.setName(\"web-pod\");\n"
    "        pod.setServiceAccountName(\"web-sa\");\n"
    "        cluster.setPods(List.of(pod));\n"
    "        Map<String, String> sel = new HashMap<>();\n"
    "        sel.put(\"app\", \"web\");\n"
    "        ServiceSnapshot svc = new ServiceSnapshot();\n"
    "        svc.setName(\"web-service\");\n"
    "        svc.setSelector(sel);\n"
    "        cluster.setServices(List.of(svc));\n"
    "        DeploymentSnapshot dep = new DeploymentSnapshot();\n"
    "        dep.setName(\"web-deployment\");\n"
    "        dep.setReplicas(3);\n"
    "        dep.setSelector(sel);\n"
    "        cluster.setDeployments(List.of(dep));\n"
    "        SecretSnapshot secret = new SecretSnapshot();\n"
    "        secret.setName(\"db-password\");\n"
    "        secret.setSecretType(\"Opaque\");\n"
    "        cluster.setSecrets(List.of(secret));\n"
    "        PersistentVolumeSnapshot pv = new PersistentVolumeSnapshot();\n"
    "        pv.setName(\"data-pv\");\n"
    "        pv.setStorageClassName(\"standard\");\n"
    "        cluster.setPersistentVolumes(List.of(pv));\n"
    "        PersistentVolumeClaimSnapshot pvc = new PersistentVolumeClaimSnapshot();\n"
    "        pvc.setName(\"data-pvc\");\n"
    "        pvc.setVolumeName(\"data-pv\");\n"
    "        pvc.setStorageClassName(\"standard\");\n"
    "        cluster.setPersistentVolumeClaims(List.of(pvc));\n"
    "        ClusterRoleBindingSnapshot crb = new ClusterRoleBindingSnapshot();\n"
    "        crb.setName(\"admin-binding\");\n"
    "        crb.setSubjectName(\"admin-sa\");\n"
    "        crb.setClusterRoleName(\"cluster-admin\");\n"
    "        cluster.setClusterRoleBindings(List.of(crb));\n"
    "        assertEquals(\"test-cluster\", cluster.getClusterName());\n"
    "        assertEquals(1, cluster.getNamespaces().size());\n"
    "        assertEquals(\"production\", cluster.getNamespaces().get(0).getName());\n"
    "        assertEquals(\"worker-1\", cluster.getNodes().get(0).getName());\n"
    "        assertEquals(\"web-sa\", cluster.getPods().get(0).getServiceAccountName());\n"
    "        assertEquals(\"web\", cluster.getServices().get(0).getSelector().get(\"app\"));\n"
    "        assertEquals(3, cluster.getDeployments().get(0).getReplicas());\n"
    "        assertEquals(\"Opaque\", cluster.getSecrets().get(0).getSecretType());\n"
    "        assertEquals(\"standard\", cluster.getPersistentVolumes().get(0).getStorageClassName());\n"
    "        assertEquals(\"data-pv\", cluster.getPersistentVolumeClaims().get(0).getVolumeName());\n"
    "        assertEquals(\"cluster-admin\", cluster.getClusterRoleBindings().get(0).getClusterRoleName());\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void ingressSnapshot_serviceNameRoundTrips() {\n"
    "        IngressSnapshot ingress = new IngressSnapshot();\n"
    "        ingress.setName(\"web-ingress\");\n"
    "        ingress.setServiceName(\"web-service\");\n"
    "        assertEquals(\"web-ingress\", ingress.getName());\n"
    "        assertEquals(\"web-service\", ingress.getServiceName());\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void roleBindingSnapshot_subjectAndRoleNameRoundTrip() {\n"
    "        RoleBindingSnapshot rb = new RoleBindingSnapshot();\n"
    "        rb.setSubjectName(\"dev-sa\");\n"
    "        rb.setRoleName(\"developer-role\");\n"
    "        assertEquals(\"dev-sa\", rb.getSubjectName());\n"
    "        assertEquals(\"developer-role\", rb.getRoleName());\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void clusterRoleSnapshot_rulesRoundTrip() {\n"
    "        RbacRuleSnapshot rule = new RbacRuleSnapshot();\n"
    "        rule.setApiGroups(List.of(\"*\"));\n"
    "        rule.setResources(List.of(\"*\"));\n"
    "        rule.setVerbs(List.of(\"*\"));\n"
    "        rule.setResourceNames(List.of());\n"
    "        ClusterRoleSnapshot cr = new ClusterRoleSnapshot();\n"
    "        cr.setName(\"cluster-admin\");\n"
    "        cr.setRules(List.of(rule));\n"
    "        assertNull(cr.getNamespace());\n"
    "        assertEquals(\"cluster-admin\", cr.getName());\n"
    "        assertEquals(1, cr.getRules().size());\n"
    "        assertTrue(cr.getRules().get(0).getVerbs().contains(\"*\"));\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void replicaSetSnapshot_fieldsRoundTrip() {\n"
    "        Map<String, String> sel = new HashMap<>();\n"
    "        sel.put(\"app\", \"backend\");\n"
    "        ReplicaSetSnapshot rs = new ReplicaSetSnapshot();\n"
    "        rs.setName(\"backend-rs\");\n"
    "        rs.setReplicas(2);\n"
    "        rs.setSelector(sel);\n"
    "        assertEquals(2, rs.getReplicas());\n"
    "        assertEquals(\"backend\", rs.getSelector().get(\"app\"));\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void serviceAccountSnapshot_commonFieldsRoundTrip() {\n"
    "        ServiceAccountSnapshot sa = new ServiceAccountSnapshot();\n"
    "        sa.setUid(\"sa-uid-001\");\n"
    "        sa.setName(\"web-sa\");\n"
    "        sa.setNamespace(\"default\");\n"
    "        assertEquals(\"sa-uid-001\", sa.getUid());\n"
    "        assertEquals(\"web-sa\", sa.getName());\n"
    "        assertEquals(\"default\", sa.getNamespace());\n"
    "    }\n"
    "\n"
    "    @Test\n"
    "    void configMapSnapshot_commonFieldsRoundTrip() {\n"
    "        ConfigMapSnapshot cm = new ConfigMapSnapshot();\n"
    "        cm.setName(\"app-config\");\n"
    "        cm.setNamespace(\"default\");\n"
    "        assertEquals(\"app-config\", cm.getName());\n"
    "        assertEquals(\"default\", cm.getNamespace());\n"
    "    }\n"
    "}\n"
)

path = os.path.join(test_base, "SnapshotDtoTest.java")
with open(path, "w", encoding="utf-8", newline="\n") as f:
    f.write(content)
print("Test file written.")